version: '3.8'
services:
  zenml:
    image: zenmldocker/zenml-server
    container_name: zenml
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - zenml_data:/app/.zenconfig
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  zenml_data:
