model:
  name: ibm-granite/granite-4.0-h-tiny
vllm:
  provider_config: vllm_single_card
  overrides:
    kv_cache_memory: 0
    gpu_memory_utilization: 0.95
    port: 20502
    trust_remote_code: true
task_defaults:
  log_samples: true
  cuda_devices: '2'
tasks:
- latam_board
metadata:
  max_context_length: 131072
  is_multimodal: false
  model_type: granitemoehybrid
  detected_from_config: true
  generated_at: '2025-10-15T16:16:24.600304'
  gpu_type: single
