# Structured data extraction evaluation task configuration

# Task identification
name: "structured_extraction"
description: "Structured data extraction using guided JSON schema"

# Task-specific parameters
task_name: "structured_extraction"
dataset_file: "paraloq_data.jsonl"
dataset_name: "paraloq/json_data_extraction"

# Prompt templates
prompts:
  system: |
    You are a precise data extraction assistant. Extract information from the provided text according to the given JSON schema. Only extract information explicitly stated in the text. If information for a field is not present, use null as appropriate.
  user: |
    Text:
    {text}

    Extract information according to this JSON schema:
    {schema}

    Output valid JSON matching the schema exactly.

# Default evaluation parameters
defaults:
  batch_size: 20  # Number of concurrent async requests
  log_samples: false
  temperature: 0.0
  max_tokens: 2048
  timeout: 120
  max_retries: 3

# Metrics configuration
metrics:
  extraction_quality_score:
    enabled: true
    weights:
      schema_validity: 0.20
      field_f1_partial: 0.60
      inverted_hallucination: 0.20
  
  partial_matching:
    string:
      token_overlap_weight: 0.5
      levenshtein_weight: 0.3
      containment_weight: 0.2
      exact_threshold: 0.95
      partial_threshold: 0.50
    number:
      relative_tolerance: 0.001
      absolute_tolerance: 1e-6
    array:
      method: "jaccard"
      partial_credit: true
  
  normalization:
    case_sensitive: false
    normalize_whitespace: true
    unicode_normalize: true

# Output configuration
output:
  subdirectory: "structured_extraction"

