# Example Configuration with Limit for Testing
# This config uses --limit 10 for fast testing runs

model:
  name: "google/gemma-3-270m"
  dtype: "float16" 
  max_length: 16384

evaluation:
  tasks: "belebele_spa_Latn"
  device: "cuda:3"
  batch_size: "auto:4"
  output_path: "/home/mauro/dev/lm-evaluation-harness/output"
  log_samples: true
  limit: 10  # Only evaluate 10 examples per task for quick testing

wandb:
  entity: "surus-lat"
  project: "LATAM-leaderboard"

upload:
  script_path: "/home/mauro/dev/leaderboard"
  script_name: "run_pipeline.py"

# Logging configuration
logging:
  log_dir: "logs"  # Directory to store log files

venvs:
  lm_eval: "/home/mauro/dev/lm-evaluation-harness"
  leaderboard: "/home/mauro/dev/leaderboard"
