# Benchy Configuration - Qwen Model
model:
  name: "Qwen/Qwen3-4B-Instruct-2507"
  dtype: "float16" 
  max_length: 16384

evaluation:
  tasks: "latam"
  device: "cuda"
  batch_size: "auto:4"
  output_path: "/home/mauro/dev/lm-evaluation-harness/output"
  log_samples: true

wandb:
  entity: "surus-lat"
  project: "LATAM-leaderboard"

upload:
  script_path: "/home/mauro/dev/leaderboard"
  script_name: "run_pipeline.py"

venvs:
  lm_eval: "/home/mauro/dev/lm-evaluation-harness"
  leaderboard: "/home/mauro/dev/leaderboard"
